Accept compiler options when building app
nubank/vessel pull request #32
Opened 2024-01-03 20:25 UTC by miorimmax

* **Please check if the PR fulfills these requirements**
- [ ] There is an open issue describing the problem that this pr intents to solve.
    - [ ] You have a descriptive commit message with a short title (first line).
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added / updated (for bug fixes / features).

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) Feature

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2024-01-04 13:42 UTC, miorimmax commented
Looks like the PR checks are not triggering for some reason, anything I should do?

2024-01-04 15:14 UTC, alan-ghelardi commented on src/vessel/program.clj
> +             :validate [#(or (nil? %) (map? %)) "Compiler options must be a valid Clojure map"]]
💅  maybe it's worth moving this sexpr to a def since you are duplicating it below.

2024-01-04 15:15 UTC, alan-ghelardi approved these changes
lgtm. I'll have a look why the Action didn't trigger 😕

2024-01-04 17:37 UTC, alan-ghelardi commented
I changed the workflow to trigger on pull_request events. Could you rebase onto the main branch, please? Also, most likely, you'll need to enable actions on your fork if they aren't enabled by default. Last, if possible, add a new entry to the changelog with a brief explanation about your change. Just put a new Added section under the Unreleased one. When we trigger a release, the changelog is bumped automatically.

2024-02-01 17:20 UTC, alan-ghelardi requested changes
I'm just requesting a change in the changelog to avoid breaking the release process. The feature itself is fine.

2024-02-01 17:20 UTC, alan-ghelardi commented on CHANGELOG.md
> +## [0.2.149] - 2024-01-31
Please, remove this title. The release script alters the changelog automatically during the release flow. Just keep the added section under the unreleased one.

2024-02-01 19:44 UTC, alan-ghelardi approved these changes

2024-02-01 19:44 UTC, merged